# Generated by Django 4.0.3 on 2022-04-07 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('type', models.TextField(choices=[('NUM', 'Numeric value'), ('TEXT', 'Text or Characters'), ('BOOL', 'Yes or No'), ('DATE', 'Date and Time')])),
            ],
        ),
        migrations.CreateModel(
            name='BooleanItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('value', models.BooleanField(blank=True, null=True)),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='DateItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('value', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='NumericItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('value', models.TextField(blank=True, default='')),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('kis_id', models.CharField(max_length=8)),
                ('gender', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('main_diagnosis', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('dataforms', models.ManyToManyField(to='api.dataformtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='dataformtemplate',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.item'),
        ),
    ]
