# Generated by Django 4.0.2 on 2022-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
