# Generated by Django 4.0.2 on 2022-02-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_kis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
    ]
