# Generated by Django 4.0.2 on 2022-02-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_created_at_patient_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
    ]
