# Generated by Django 4.0.2 on 2022-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_patient_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='kis_id',
            field=models.CharField(max_length=8),
        ),
    ]
